import numpy as np
from collections import OrderedDict

RANDOM_SEED = 10

USE_CHEAP_LOCA_MODEL = False
CHEAP_LOCA_NORMALISE_FOCUS_SHIFT = False
CHEAP_LOCA_CUTOFF = 0.1  # > 0.04 or so is not recommended

POLYCHROMATIC_NUM_WAVELENGTHS = 9
MODEL_WVLS = np.linspace(0.42, 0.65, POLYCHROMATIC_NUM_WAVELENGTHS + 2)[1:-1]
# POLYWEIGHTS = 0
# MODEL_WVLS = np.array([0.45, 0.62])

SPACIAL_FREQS = np.arange(4, 32, 2) / 64

SAVE_RESULTS = True

ENFORCE_BOUNDS_IN_COST = False

COST_WEIGHT_LINE_DIFF = 0e-1
COST_WEIGHT_MEAN_SQUARES = 1000
COST_WEIGHT_PEAK_LOCATIONS = 0.000
COST_WEIGHT_PEAKINESS = 0.000

COST_WEIGHT_XMODS = 1.0

PRYSM_Q_FALLBACK = 2
DEFAULT_SAMPLES = 256
USE_CUDA = True
PRECISION = 64 if USE_CUDA else 64
CUDA_PROCESSES = 2
CUDA_CPU_PROCESSES = 2
CPU_ONLY_PROCESSES = 1
CPU_GPU_ARRAYSIZE_BOUNDARY = 144
CPU_GPU_FFTSIZE_BOUNDARY_FINETUNE = False
FINETUNE_MIN = 128
FINETUNE_MAX = 384
MASK_CACHE_SIZE = 160

ENABLE_PUPIL_DISTORTION = True


PSF_SPLINE_ORDER = 3

Q_AUTOSIZE_SCALAR = 1
PHASE_AUTOSIZE_SCALAR = 0.65

DF_STEP_TOLERANCE = 2.1

MAXITER = 600

DISABLE_MULTIPROCESSING = False
LIVE_PLOTTING = not DISABLE_MULTIPROCESSING

BASE_WAVELENGTH = 0.575

EXTREME_FOCUS_WEIGHT = 0.9
HIGH_FREQUENCY_WEIGHT = 0.9

PLOT_ALPHAS = np.array([1,0,0,1,0,0,1,0,0,0,1,0,0])
PLOT_LINES = np.array([0,1,2,3,5,6,7,8,9,10,11,12,13])[PLOT_ALPHAS > 0.5]
PLOT_ALPHAS = PLOT_ALPHAS[PLOT_ALPHAS > 0.5]

DIVIDE_BY_APERTURE = lambda f, b=None: 1.0 / f
MULTIPLY_BY_APERTURE = lambda f, b=None: f
DIVIDE_BY_BASE_APERTURE = lambda f, b=None: 1.0 / b
MULTIPLY_BY_BASE_APERTURE = lambda f, b=None: b
NOP = lambda f, b=None: 1.0

ZERNIKE_SCHEME = "FRINGE"

COST_MULTIPLIER = 1

ZLIMIT = 7
ZINIT = 0

DEFAULT_SCALE = 2e-1

HIDDEN_COST_SCALE = 2e-3

OPT_PER_FOCUSSET = True
OPT_SHARED = False
OPT_PER_FIELD = "PER_FIELD"
LOCK = "LOCK"

PARAMS_OPTIONS = OrderedDict(
    # param_name=(Min, Initial, Max, normalise_with_aperture, per_focusset)
    df_offset=(None, None, None, NOP, OPT_PER_FOCUSSET, DEFAULT_SCALE * 0.1),
    df_step=(0.07, 0.2, 0.7, lambda f, b: 1.0 / f**1, OPT_PER_FOCUSSET, DEFAULT_SCALE * 0.1),
    df_each=(-0.05, 0.0, 0.05, NOP, OPT_PER_FIELD, DEFAULT_SCALE),
    z2=(-ZLIMIT, ZINIT, ZLIMIT, DIVIDE_BY_BASE_APERTURE, LOCK, DEFAULT_SCALE),
    z3=(-ZLIMIT, ZINIT, ZLIMIT, DIVIDE_BY_BASE_APERTURE, LOCK, DEFAULT_SCALE),
    z5=(-ZLIMIT, ZINIT, ZLIMIT, DIVIDE_BY_BASE_APERTURE, OPT_SHARED, DEFAULT_SCALE),
    z6=(-ZLIMIT, ZINIT, ZLIMIT, DIVIDE_BY_BASE_APERTURE, OPT_SHARED, DEFAULT_SCALE),
    z7=(-ZLIMIT, ZINIT, ZLIMIT, DIVIDE_BY_BASE_APERTURE, OPT_SHARED, DEFAULT_SCALE),
    z8=(-ZLIMIT, ZINIT, ZLIMIT, DIVIDE_BY_BASE_APERTURE, OPT_SHARED, DEFAULT_SCALE),
    z9=(-ZLIMIT, ZINIT, ZLIMIT, DIVIDE_BY_BASE_APERTURE, OPT_SHARED, DEFAULT_SCALE),
    z10=(-ZLIMIT, ZINIT, ZLIMIT, DIVIDE_BY_BASE_APERTURE, OPT_SHARED, DEFAULT_SCALE),
    z11=(-ZLIMIT, ZINIT, ZLIMIT, DIVIDE_BY_BASE_APERTURE, OPT_SHARED, DEFAULT_SCALE),
    z12=(-ZLIMIT, ZINIT, ZLIMIT, DIVIDE_BY_BASE_APERTURE, OPT_SHARED, DEFAULT_SCALE),
    z13=(-ZLIMIT, ZINIT, ZLIMIT, DIVIDE_BY_BASE_APERTURE, OPT_SHARED, DEFAULT_SCALE),
    z14=(-ZLIMIT, ZINIT, ZLIMIT, DIVIDE_BY_BASE_APERTURE, OPT_SHARED, DEFAULT_SCALE),
    z15=(-ZLIMIT, ZINIT, ZLIMIT, DIVIDE_BY_BASE_APERTURE, OPT_SHARED, DEFAULT_SCALE),
    z16=(-ZLIMIT, ZINIT, ZLIMIT, DIVIDE_BY_BASE_APERTURE, OPT_SHARED, DEFAULT_SCALE),
    z17=(-ZLIMIT, ZINIT, ZLIMIT, DIVIDE_BY_BASE_APERTURE, OPT_SHARED, DEFAULT_SCALE),
    z18=(-ZLIMIT, ZINIT, ZLIMIT, DIVIDE_BY_BASE_APERTURE, OPT_SHARED, DEFAULT_SCALE),
    z19=(-ZLIMIT, ZINIT, ZLIMIT, DIVIDE_BY_BASE_APERTURE, OPT_SHARED, DEFAULT_SCALE),
    z20=(-ZLIMIT, ZINIT, ZLIMIT, DIVIDE_BY_BASE_APERTURE, OPT_SHARED, DEFAULT_SCALE),
    z21=(-ZLIMIT, ZINIT, ZLIMIT, DIVIDE_BY_BASE_APERTURE, OPT_SHARED, DEFAULT_SCALE),
    z22=(-ZLIMIT, ZINIT, ZLIMIT, DIVIDE_BY_BASE_APERTURE, OPT_SHARED, DEFAULT_SCALE),
    z23=(-ZLIMIT, ZINIT, ZLIMIT, DIVIDE_BY_BASE_APERTURE, OPT_SHARED, DEFAULT_SCALE),
    z24=(-ZLIMIT, ZINIT, ZLIMIT, DIVIDE_BY_BASE_APERTURE, OPT_SHARED, DEFAULT_SCALE),
    z25=(-ZLIMIT, ZINIT, ZLIMIT, DIVIDE_BY_BASE_APERTURE, OPT_SHARED, DEFAULT_SCALE),
    z26=(-ZLIMIT, ZINIT, ZLIMIT, DIVIDE_BY_BASE_APERTURE, OPT_SHARED, DEFAULT_SCALE),
    z27=(-ZLIMIT, ZINIT, ZLIMIT, DIVIDE_BY_BASE_APERTURE, OPT_SHARED, DEFAULT_SCALE),
    z28=(-ZLIMIT, ZINIT, ZLIMIT, DIVIDE_BY_BASE_APERTURE, OPT_SHARED, DEFAULT_SCALE),
    z29=(-ZLIMIT, ZINIT, ZLIMIT, DIVIDE_BY_BASE_APERTURE, OPT_SHARED, DEFAULT_SCALE),
    z30=(-ZLIMIT, ZINIT, ZLIMIT, DIVIDE_BY_BASE_APERTURE, OPT_SHARED, DEFAULT_SCALE),
    z31=(-ZLIMIT, ZINIT, ZLIMIT, DIVIDE_BY_BASE_APERTURE, OPT_SHARED, DEFAULT_SCALE),
    z32=(-ZLIMIT, ZINIT, ZLIMIT, DIVIDE_BY_BASE_APERTURE, OPT_SHARED, DEFAULT_SCALE),
    z33=(-ZLIMIT, ZINIT, ZLIMIT, DIVIDE_BY_BASE_APERTURE, OPT_SHARED, DEFAULT_SCALE),
    z34=(-ZLIMIT, ZINIT, ZLIMIT, DIVIDE_BY_BASE_APERTURE, OPT_SHARED, DEFAULT_SCALE),
    z35=(-ZLIMIT, ZINIT, ZLIMIT, DIVIDE_BY_BASE_APERTURE, OPT_SHARED, DEFAULT_SCALE),
    z36=(-ZLIMIT, ZINIT, ZLIMIT, DIVIDE_BY_BASE_APERTURE, OPT_SHARED, DEFAULT_SCALE),
    z37=(-ZLIMIT, ZINIT, ZLIMIT, DIVIDE_BY_BASE_APERTURE, OPT_SHARED, DEFAULT_SCALE),
    z38=(-ZLIMIT, ZINIT, ZLIMIT, DIVIDE_BY_BASE_APERTURE, OPT_SHARED, DEFAULT_SCALE),
    z39=(-ZLIMIT, ZINIT, ZLIMIT, DIVIDE_BY_BASE_APERTURE, OPT_SHARED, DEFAULT_SCALE),
    z40=(-ZLIMIT, ZINIT, ZLIMIT, DIVIDE_BY_BASE_APERTURE, OPT_SHARED, DEFAULT_SCALE),
    z41=(-ZLIMIT, ZINIT, ZLIMIT, DIVIDE_BY_BASE_APERTURE, OPT_SHARED, DEFAULT_SCALE),
    z42=(-ZLIMIT, ZINIT, ZLIMIT, DIVIDE_BY_BASE_APERTURE, OPT_SHARED, DEFAULT_SCALE),
    z43=(-ZLIMIT, ZINIT, ZLIMIT, DIVIDE_BY_BASE_APERTURE, OPT_SHARED, DEFAULT_SCALE),
    z44=(-ZLIMIT, ZINIT, ZLIMIT, DIVIDE_BY_BASE_APERTURE, OPT_SHARED, DEFAULT_SCALE),
    z45=(-ZLIMIT, ZINIT, ZLIMIT, DIVIDE_BY_BASE_APERTURE, OPT_SHARED, DEFAULT_SCALE),
    z46=(-ZLIMIT, ZINIT, ZLIMIT, DIVIDE_BY_BASE_APERTURE, OPT_SHARED, DEFAULT_SCALE),
    z47=(-ZLIMIT, ZINIT, ZLIMIT, DIVIDE_BY_BASE_APERTURE, OPT_SHARED, DEFAULT_SCALE),
    z48=(-ZLIMIT, ZINIT, ZLIMIT, DIVIDE_BY_BASE_APERTURE, OPT_SHARED, DEFAULT_SCALE),
    fstop=(1 / 1.23, 1.00, 1.2, MULTIPLY_BY_APERTURE, OPT_SHARED, DEFAULT_SCALE),
    loca=(-10, 0.0, 10, DIVIDE_BY_BASE_APERTURE, OPT_SHARED, DEFAULT_SCALE),
    loca1=(-10, 0.0, 10, DIVIDE_BY_BASE_APERTURE, OPT_SHARED, DEFAULT_SCALE),
    spca=(-20, 0.00, 20, DIVIDE_BY_BASE_APERTURE, OPT_SHARED, DEFAULT_SCALE),
    spca2=(-20, 0.00, 20, DIVIDE_BY_BASE_APERTURE, OPT_SHARED, DEFAULT_SCALE),
    zero=(0, 0.0, 0.05, NOP, OPT_SHARED, DEFAULT_SCALE),
    a=(0.5, 1.0, 1.3, NOP, OPT_SHARED, DEFAULT_SCALE),
    b=(0.5, 1.0, 1.3, NOP, OPT_SHARED, DEFAULT_SCALE),
    v_slr=(0.2, 1.0, 2, NOP, OPT_SHARED, DEFAULT_SCALE),
    v_rad=(1.0, 1.0, 1.5, NOP, OPT_SHARED, DEFAULT_SCALE),
    v_x=(-1.2, 0.0, 1.2, NOP, LOCK, DEFAULT_SCALE),
    v_y=(-1.2, 0.0, 1.2, NOP, LOCK, DEFAULT_SCALE),
    tca_slr=(-0.1, 0.0, 0.1, NOP, OPT_SHARED, DEFAULT_SCALE),
    lca_x=(-1.0, 0.0, 1.0, NOP, LOCK, DEFAULT_SCALE),
    lca_y=(-1.0, 0.0, 1.0, NOP, LOCK, DEFAULT_SCALE),
    ellip=(-0.5, 0, 0.5, NOP, OPT_SHARED, DEFAULT_SCALE),

)

OPTIMISE_PARAMS = [
    'df_offset',
    'df_step',
    # 'df_each',
    # 'z2',
    # 'z3',
    'z5',
    'z6',
    'z7',
    'z8',
    'z9',
    'z10',
    'z11',
    'z12',
    'z13',
    'z14',
    'z15',
    'z16',
    # 'z17',
    # 'z18',
    # 'z19',
    # 'z20',
    # 'z21',
    # 'z22',
    # 'z23',
    # 'z24',
    'z25',
    # 'z26',
    # 'z27',
    # 'z28',
    # 'z29',
    # 'z30',
    # 'z31',
    # 'z32',
    # 'z33',
    # 'z34',
    # 'z35',
    'z36',
    # 'z37',
    # 'z38',
    # 'z39',
    # 'z40',
    # 'z41',
    # 'z42',
    # 'z43',
    # 'z44',
    # 'z45',
    # 'z46',
    # 'z47',
    # 'z48',
    'fstop',
    'loca1',
    'loca',
    'spca',
    'spca2',
    'v_slr',
    # 'v_rad',
    'tca_slr',
    'ellip',
    'a',
    'b',
]

SCALE_EXTRA = {'fstop': 3.7750127940905593, 'df_offset': 1.9268838233040835, 'df_step': 11.659412200564097, 'z5': 2.544861254111143, 'z6': 0.037362229499105316, 'z7': 1.5329821028313055, 'z8': 2.0005764203933674, 'z9': 7.789212820305486, 'z12': 4.675067234283609, 'z13': 0.2980637903874313, 'z14': 2.3164700699857232, 'z15': 3.377308821435411, 'z16': 9.659740806225251, 'z25': 11.06817635494854, 'loca1': 0.800415463675214, 'loca': 0.21466390681550063, 'spca': 1.0832760766796572, 'spca2': 0.4035409612143754, 'v_slr': 1.1147310854695922, 'tca_slr': 0.367079143997886, 'ellip': 6.903569860428498}

USE_EXISTING_PARAMETER_IF_FIXED = False

if 'loca' in OPTIMISE_PARAMS and len(MODEL_WVLS) < 3:
    print("Cannot model LOCA properly without more wavelengths!")

for param in OPTIMISE_PARAMS:
    if PARAMS_OPTIONS[param][4] == LOCK:
        raise Exception("Locked parameters cannot be optimised")

FIXED_PARAMS = []
for key in PARAMS_OPTIONS.keys():
    if key not in OPTIMISE_PARAMS:
        FIXED_PARAMS.append(key)



